# Generated by Django 3.0.3 on 2020-02-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cruise', '0002_auto_20200214_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='types',
            new_name='type',
        ),
    ]
